from snakemake.utils import min_version

# set minimum snakemake version
min_version('8.16.0')

# global workflow dependencies
conda:
    "envs/global.yaml"

# parameters from the config file
configfile: 
    'config/config.yaml'

# environment variable
envvars:
    'comtrade_apikey'

# load rules
include: 'rules/get_uncomtrade.smk'
include: 'rules/merge_uncomtrade.smk'

# target rule
rule all:
    input:
        'resources/raw_data/uncomtrade_merged.parquet.gzip'
        # expand('resources/raw_data/uncomtrade_{cmd}.parquet.gzip', cmd=config['cmdCode'])
