from snakemake.utils import min_version

# set minimum snakemake version
min_version('8.16.0')

# global workflow dependencies
conda:
    "envs/global.yaml"

# parameters from the config file
configfile: 
    'config/config.yaml'

# environment variable
envvars:
    'comtrade_apikey'

# load rules
include: 'rules/correspondence_FAO_HS.smk'
include: 'rules/get_uncomtrade.smk'
include: 'rules/wb_data.smk'
include: 'rules/plot_outliers.smk'

# target rule
rule all:
    input:
        'resources/raw_data/wb_countries_data.csv'
